WishList/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^items/', include('apps.items.urls', namespace="items")),
    url(r'^', include('apps.users.urls', namespace="users"))
]

apps/items/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.create, name="create"),
    url(r'^add_wish/$', views.add_wish, name="add_wish"),
    url(r'^delete_wish/$', views.delete_wish, name="delete_wish"),
    url(r'^remove_wish/$', views.remove_wish, name="remove_wish")
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^new/$', views.new, name="new"),
    url(r'^create/$',views.create, name='create'),
    url(r'^login/$',views.login, name='login'),
    url(r'^logout/$',views.logout, name='logout'),
    url(r'^(?P<id>\d)/$', views.show, name='show'),
    url(r'^add_item/$',views.add_item, name='add_item')
]

apps/items/models.py
from django.db import models
from ..users.models import User

class ItemManager(models.Manager):
    def validate(self,form):
        errors = []
        if len(form['name']) < 3:
            errors.append("Item name must be at least 3 characters long.")
        try: 
            self.get(name=form['name'])
            errors.append('Item already added.')
        except:
            pass
        return errors

    def create_item(self,item_data):
        creator = User.objects.get(id=item_data['creator'])
        user_wished = User.objects.get(id=item_data['user_wished'])
        
        item = self.create(
            name=item_data['name'],
            creator=creator
        )
        item.user_wished.add(user_wished)

        return item

    def add_wish(self, wish_data):
        items = Item.objects.get(id=wish_data['item_id'])
        users_wish = User.objects.get(id=wish_data['user_id'])
        wish_list_add = items.user_wished.add(users_wish)
        return wish_list_add

    def remove_wish(self, remove_data):
        items = Item.objects.get(id=remove_data['item_id'])
        users_remove = User.objects.get(id=remove_data['user_id'])
        wish_list_remove = items.user_wished.remove(users_remove)
        return wish_list_remove
    
    def delete_wish(self, delete_data):
        items_delete = Item.objects.get(id=delete_data['item_id'])
        delete_item = items_delete.delete()
        return delete_item

class Item(models.Model):
    name = models.CharField(max_length=255)
    creator = models.ForeignKey(User, related_name="items") 
    user_wished = models.ManyToManyField(User, related_name="wished_item")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ItemManager() 

apps/users/models.py
from django.db import models
import bcrypt


class UserManager(models.Manager):
    def validate(self, form):
        errors = []
        if len(form['name']) < 3:
            errors.append('Name must be at least 3 characters long')
        if len(form['username']) < 3:
            errors.append('Username must be at least 3 characters long')
        if len(form['password']) < 8:
            errors.append('Password must be 8 characters long')
        if form['password'] != form['conf_pw']:
            errors.append('Password must match')
        try:
            self.get(username=form['username'])  
            errors.append('Username already in use')
        except:
            pass

        return errors
 
    def create_user(self, user_data):
        pw_hash = bcrypt.hashpw(user_data['password'].encode(), bcrypt.gensalt())
        user = self.create(
            name=user_data['name'],
            username=user_data['username'],
            pw_hash=pw_hash
        )
        return user
    
    def login(self, form):
        user_list = self.filter(username=form['username'])
        if len(user_list) > 0:
            user = user_list[0]
            if bcrypt.checkpw(form['password'].encode(),user.pw_hash.encode()):
                return (True, user.id)
            else:
                return (False, "Email or password incorrect.")
        else:
            return (False, "Email or password incorrect.")

class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()
    def __str__(self):
        name = self.name
        return name

apps/items/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import Item

def create(req):
    if req.method != 'POST':
        print("this is not via post")
        return redirect('users:new')
    
    errors = Item.objects.validate(req.POST)
    if len(errors) > 0:
        for error in errors:
            messages.error(req, error)
    else:
        Item.objects.create_item(req.POST)
        return redirect ('users:index')

    return redirect('users:add_item')

def add_wish(req):
    if req.method != 'POST':
        return redirect('users:new')
    else:
        Item.objects.add_wish(req.POST)
        return redirect('users:index')
   
    return redirect('users:new')

def remove_wish(req):
    if req.method != 'POST':
        return redirect('users:new')
    else:
        Item.objects.remove_wish(req.POST)
        return redirect('users:index')
    
    return redirect('users:new')

def delete_wish(req):
    if req.method != 'POST':
        return redirect('users:new')
    else:
        Item.objects.delete_wish(req.POST)
        return redirect('users:index')
        
    return redirect('users:new')

apps/users/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import User
from ..items.models import Item

def index(req):
    if 'user_id' not in req.session:
        return redirect('users:new')

    context = {
        'curr_user': User.objects.get(id=req.session['user_id']),
        'your_wish_list': Item.objects.filter(user_wished=req.session['user_id']),
        'others_wish_list': Item.objects.exclude(user_wished=req.session['user_id']),
    }
    return render(req,'users/index.html', context)

def show(req, id):
    if 'user_id' not in req.session:
        return redirect('users:new')

    try:
        item = Item.objects.get(id=id)
    except:
        return redirect('users:index')

    context = {
        'items': item,
        'users_wish': item.user_wished.all()
    }

    return render(req, 'users/show.html', context)

def new(req):
    return render(req, 'users/new.html')

def create(req):
    if req.method != 'POST':
        return redirect('users:new')

    # messages.add_message(request, LOGINERROR, '')
    errors = User.objects.validate(req.POST)
    if len(errors) > 0:
        for error in errors:
            messages.error(req, error)
    else:
        user = User.objects.create_user(req.POST)
        req.session['user_id'] = user.id
        req.session['name'] = user.name
        return redirect('users:index')

    return redirect('users:new')

def login(req):
    if req.method != 'POST':
        return redirect('users:new')

    valid, response = User.objects.login(req.POST)
    if valid == True:
        req.session['user_id'] = response
        return redirect('users:index')
    else:
        messages.error(req, response)
    return redirect('users:new')

def logout(req):
    req.session.clear()
    return redirect('users:new')

def add_item(req):
    if 'user_id' not in req.session:
        return redirect('users:new')
    return render(req, 'users/add.html')

apps/users/templates/users/add.html
{% extends './layout.html' %}

{% block body %}
    <div id="main_content">
        <h3>Create a new wish list item:</h3>
        {% if messages %}
            <ul class="messages error">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="{% url 'items:create' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="creator" value="{{ request.session.user_id }}">
            <input type="hidden" name="user_wished" value="{{ request.session.user_id }}">
            <!-- <label for="name">Item/Product:</label> -->
            <input type="text" class="form-control col-6" name="name">
            <br>
            <input class="btn add_item" type="submit" value="Add">
        </form>
    </div>
{% endblock %}

apps/users/templates/users/index.html
{% extends './layout.html' %}

{% block title %} Home {% endblock %}

{% block head %}

{% endblock %}

{% block nav %}
    <h3> Hello {{ curr_user.name }}!</h3>
{% endblock %}

{% block body %}
<div id="main_content">
    <div class="wished">
        <h3>My Wish List:</h3>
        {% if your_wish_list %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">Added by</th>
                        <th scope="col">Date Added</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in your_wish_list %}
                        <tr>
                            <td><a href="{{ item.id }}/">{{ item.name }}</a></td>
                            <td>{{ item.creator }}</td>
                            <td>{{ item.created_at|date:"M d, Y" }}</a></td>
                            <td>
                                {% if item.creator.id != request.session.user_id %}
                                    <form action="{% url 'items:remove_wish' %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="user_id" value="{{ request.session.user_id }}">
                                        <input type="hidden" name="item_id" value="{{ item.id }}">
                                        <input class="btn btn_table remove" type="submit" value="Remove">
                                    </form>
                                {% endif %}
                                {% if item.creator.id == request.session.user_id %}
                                    <form action="{% url 'items:delete_wish' %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="user_id" value="{{ request.session.user_id }}">
                                        <input type="hidden" name="item_id" value="{{ item.id }}">
                                        <input class="btn btn_table delete" type="submit" value="Delete">
                                    </form>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>

    <div class="not_wished">
        <h3>Items not added:</h3>
        {% if others_wish_list %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">Added by</th>
                        <th scope="col">Date Added</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in others_wish_list %}
                        <tr>
                            <td><a href="{{ item.id }}/">{{ item.name }}</a></td>
                            <td>{{ item.creator }}</td>
                            <td>{{ item.created_at|date:"M d, Y" }}</a></td>
                            <td>
                                <form action="{% url 'items:add_wish' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="user_id" value="{{ request.session.user_id }}">
                                    <input type="hidden" name="item_id" value="{{ item.id }}">
                                    <input class="btn btn_table add" type="submit" value="Add">
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
    <a class="btn add_item" href="{% url 'users:add_item' %}">Add New Item</a>
</div>


{% endblock %}

apps/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Rock+Salt|Quicksand|Khula" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
    <title>{% block title %} {% endblock %}</title>
    {% block head %} {% endblock %}
</head>
<body>
    <div id="container">
        <div class="navbar">
            {% if 'user_id' in request.session %}
                <a href="{% url 'users:index' %}" class="btn">Home</a>
                {% block nav %}<h5> Wish for anything you want! </h5>{% endblock %}
                <a href="{% url 'users:logout' %}" class="btn">Logout</a>
            {% else %}
                <div></div>
                <h5>Wish for anything you want!</h5>
                <div></div>
            {% endif %}
        </div>
        {% block body %} {% endblock %}
    </div>

</body>
</html>

apps/users/templates/users/new.html
 {% extends './layout.html' %}

{% block title %} Wish List {% endblock %}

{% block head %} 
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
{% endblock %}

{% block body %}
    <div id="title_page">
        <h1>Wish List</h1>
    </div>
    <div id="main-content">
        <div class="error">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        <div class="register">
            <h2>Register:</h2>
            <form action="{% url 'users:create' %}" method="post">
            {% csrf_token %}
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name">
                <br>
                <label for="username">Username:</label>
                <input type="text" class="form-control" name="username">
                <br>
                <label for="password">Password:</label>
                <input type="password" class="form-control" name="password">
                <br>
                <label for="conf_pw">Confirm Password:</label>
                <input type="password" class="form-control" name="conf_pw">
                <br>
                <input class="btn btn-outline-dark" type="submit" value="Register">
            </form>
        </div>
        <div class="login">
            <h2>Login:</h2>
            <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" class="form-control" name="username">
                <br>
                <label for="password">Password:</label>
                <input type="password" class="form-control" name="password">
                <br>
                <input class="btn btn-outline-dark" type="submit" value="Login">
            </form>
        </div>
    </div>
{% endblock %}

apps/users/templates/users/show.html
{% extends './layout.html' %}

{% block title %} {{ items.name }} {% endblock %}

{% block nav %} <h3>{{ items.name }}</h3> {% endblock %}

{% block body %}
    <div id="main_content">
        <h4>People who also want the {{ items.name }}!</h4>
        <ul>
            {% for user in users_wish %}
                <li>{{ user.name }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}